### PR TITLE
parallelize creation of indy connections

### PR DESCRIPTION
**Pull request by dennisn00**
Speed up `IndyConnector.openIndyConnections()` by parallelizing it. This reduces runtime from 2-3 minutes to 20-40 seconds

### CODE REVIEW

**Comment by peacekeeper** [comment]
This looks great, thank you.. I'll run a few tests and then merge it if everything works.

**Comment by peacekeeper** [comment]
Hmm when I try this inside a Kubernetes pod, the container gets killed with an OutOfMemory error.. Not sure why parallel opening of the Indy connections would consume more memory. Will experiment a bit more..

**Comment by dennisn00** [comment]
I only tested with Docker and it ran fine and didn't seem to consume crazy amounts of memory. I will try to use it in Kubernetes, but I have no experience with that

**Comment by peacekeeper** [comment]
I experimented with this a bit more.. Running with Docker locally works fine, but as I said running in a Kubernetes clusters gives me an out-of-memory error. So somehow, opening pools in parallel seems to consume more memory. Still, I think this is a very useful feature.

How about adding a parameter here in this library, and an environment variables in https://github.com/decentralized-identity/uni-resolver-driver-did-indy, to make it configurable whether or not to open pools in parallel?

I worked on this on a branch: https://github.com/danubetech/libindy-common-java/tree/synchronized_collections

If you agree, I'll merge your PR here and then add my changes on top of it.

**Comment by dennisn00** [comment]
Yes, thats sounds good. I would just add some documentation somewhere. It might not be obvious for everyone that an OutOfMemory Error is related to the openParallel setting

**Comment by peacekeeper** [comment]
Great, I merged this here and created https://github.com/danubetech/libindy-common-java/pull/3

**Pull request merged**
